kind: Deployment
apiVersion: apps/v1
metadata: 
   name: flipkart
spec:
   replicas: 2
   selector: 
    matchLabels: 
     name: deployment
   template:
     metadata:
       name: feature
       labels:
         name: deployment
     spec:
      containers:
        - name: login
          image: ubuntu
          command: ["/bin/bash", "-c", "while true; do echo amplogin; sleep 2; done"] 
